elasticsearch:
  host: localhost # default: please don't change this if not necessary
  port: 9200 # default: please don't change this if not necessary
  index_name: bench4bl # NECESSARY: change this to your index name.
#  index_name: bench4bl_fixed # NECESSARY: change this to your index name.
#  index_name: bench4blsum # NECESSARY: change this to your index name.
#  index_name: bench4blaj # NECESSARY: change this to your index name.

Fields:
  project: keyword
  sub_project: keyword
  version: keyword
  source_code: text
  file_url: keyword
#  bug_id: keyword
#  bug_summary: text
#  bug_description: text
